#!/bin/bash
# Select Host entry with fzf and open with ssh

# Bash strict mode.
# See http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

ssh $(sed '/^Host/!d' ~/.ssh/config | awk '{ print $2 }' | sed '/\*/d' | fzf)
